### ISSUE TITLE
where is config_all.yaml

### ISSUE THREAD

**Issue by WAN-M** [zidiyang/omni_swarm_docker#2]
Appreciate your work! I'm trying to run your docker image on my server but I get some trouble. You mentioned in readme "modify the config_all.yaml", so I assume that a template yaml file is offered. However, I don't find it anywhere, no matter in your repo or docker image. I'll be most grateful if you can answer me where I can find it or how it looks like!

**Comment by zidiyang** [comment]
The "config_all.yaml" is provided in the datasets_download_website offered in README, alongside the rosbag you downloaded.

**Comment by WAN-M** [comment]
thank you so much!
